"""
===============================================================================
LEXORA WEB EDITOR - FLASK APPLICATION
Version: 1.0.0
Author: Ashish Mishra

Description:
    Production-ready Flask web server for the Lexora programming language.
    Provides a browser-based IDE with live code execution, file upload/download,
    and comprehensive documentation.

Features:
    - Real-time code execution in browser
    - File upload/download support (.lx files)
    - Syntax-highlighted code editor (CodeMirror)
    - Interactive documentation
    - Responsive, modern UI
    - Output capture and display

Routes:
    GET  /         - Landing page
    GET  /editor   - Web-based IDE
    GET  /docs     - Documentation
    GET  /about    - Project information
    POST /execute  - Code execution endpoint

Usage:
    Development:
        python app.py
    
    Production (with Gunicorn):
        gunicorn -w 4 -b 0.0.0.0:5000 app:app
    
    Command (from lexora command):
        lexora-editor

Environment Variables:
    FLASK_ENV=production  - Set production mode
    PORT=5000            - Custom port (default: 5000)

License:
    MIT License - See LICENSE file for details
===============================================================================
"""

# =============================================================================
# IMPORTS - Dependencies
# =============================================================================
from flask import Flask, render_template, request, jsonify  # Flask web framework
from io import StringIO  # String I/O operations
import sys  # System-specific parameters
import os   # Operating system interface
from lexora.lexora import SimpleEnglishInterpreter  # Lexora interpreter

# =============================================================================
# FLASK APPLICATION INITIALIZATION
# =============================================================================
app = Flask(__name__)  # Create Flask application instance
interpreter = SimpleEnglishInterpreter()  # Initialize Lexora interpreter

# =============================================================================
# HELPER CLASS: OutputCapture - Console Output Interceptor
# =============================================================================
class OutputCapture:
    """
    Captures stdout from print() statements during code execution.
    
    This class replaces sys.stdout temporarily to capture all output
    generated by Display commands and other print operations.
    
    Attributes:
        output (list): List of captured output strings
    
    Example:
        >>> capture = OutputCapture()
        >>> sys.stdout = capture
        >>> print("Hello")
        >>> sys.stdout = sys.__stdout__
        >>> print(''.join(capture.output))  # Outputs: Hello
    """
    def __init__(self):
        self.output = []

    def write(self, text):
        self.output.append(text)

    def flush(self):
        pass

@app.route('/')
def index():
    """Render the landing page"""
    return render_template('index.html')

@app.route('/editor')
def editor():
    """Render the code editor page"""
    return render_template('editor.html')

@app.route('/docs')
def docs():
    """Render the documentation page"""
    return render_template('docs.html')

@app.route('/about')
def about():
    """Render the about page with project info"""
    return render_template('about.html')

@app.route('/execute', methods=['POST'])
def execute():
    """Execute Lexora code and return the output"""
    code = request.json.get('code', '')
    
    # Create a fresh interpreter for each execution to avoid state pollution
    current_interpreter = SimpleEnglishInterpreter()
    
    # Capture stdout to get the output
    stdout = sys.stdout
    output_capture = OutputCapture()
    sys.stdout = output_capture
    
    try:
        # Execute the code as a script
        lines = code.split('\n')
        current_interpreter.execute_script(lines)
        
        # Restore stdout and return results
        sys.stdout = stdout
        output_str = ''.join(output_capture.output)
        return jsonify({
            'status': 'success',
            'output': output_str if output_str else "Program finished with no output."
        })
    
    except Exception as e:
        sys.stdout = stdout
        return jsonify({
            'status': 'error',
            'error': str(e)
        })

@app.route('/health')
def health():
    """Health check endpoint for production monitoring"""
    return jsonify({'status': 'healthy'})

if __name__ == '__main__':
    # Get port from environment variable (for Render/Railway deployment)
    port = int(os.environ.get('PORT', 5001))
    
    # In production/cloud environments, always bind to 0.0.0.0
    host = '0.0.0.0' if os.environ.get('PORT') or os.environ.get('FLASK_ENV') == 'production' else '127.0.0.1'
    debug_mode = os.environ.get('FLASK_ENV') != 'production'
    
    print(f"🚀 Starting Lexora Server on {host}:{port} (Debug: {debug_mode})")
    app.run(debug=debug_mode, port=port, host=host)

def run_server():
    """Entry point for lexora-editor command"""
    import webbrowser
    import threading
    
    # Open browser after a short delay
    def open_browser():
        import time
        time.sleep(1.5)  # Wait for server to start
        webbrowser.open('http://localhost:5001')
    
    # Start browser in separate thread
    threading.Timer(0, open_browser).start()
    
    # Run the Flask app
    print("\n🚀 Starting Lexora Editor...")
    print("📝 Opening browser at http://localhost:5001")
    print("⚡ Press Ctrl+C to stop the server\n")
    
    try:
        app.run(debug=False, port=5001, host='127.0.0.1')
    except KeyboardInterrupt:
        print("\n\n👋 Lexora Editor stopped.")